apiVersion: apps/v1
kind: Deployment
metadata:
  name: godaspringboot
spec:
  selector:
    matchLabels:
      app: godaspringboot
  replicas: 1 
  template: 
    metadata:
      labels:
        app: godaspringboot
    spec:
      containers:
      - name: godaspringboot
        image: godaprojects/goda-eks-jenkins-spinnaker-poc
        ports:
        - containerPort: 3030
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: godaspringboot
  namespace: spinnaker
spec:
  type: LoadBalancer
  selector:
    app: godaspringboot
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3030

